[book]
title = "Dirifin"
authors = ["Macohi"]
language = "en"
src = "docs"

[output.html]
smart-punctuation = true
mathjax-support = true
hash-files = true

[output.html.playground]
editable = true
line-numbers = true